사용자 회원가입 및 로그인 API
Wanted-Pre-Onboarding-Team-E/lets-go-here pull request #11
Opened 2023-11-02 07:29 UTC by laetipark

## 🚀 이슈 번호
#1 사용자 회원가입 및 로그인 API
<br>

## 💡 변경 이유
사용자 회원가입 및 로그인 API 추가
<br>

## 🔑 주요 변경사항
- jwt 인증 및 로그인 관련 모듈 추가
- 회원가입 및 로그인 관련 코드 추가
- 성공/실패 메시지 추가
<br>

## 📷 테스트 결과
### 사용자 회원 가입
#### Request
```json
{
  "username": "test10",
  "password": "11234567890@@",
  "confirmPassword": "11234567890@@"
}
```

#### Response(201)
{
  "message": "회원가입 성공",
  "data": {
  "creatableUser": "test10",
  "passwordValid": true
  }
}

#### Fail(400)
{
  "message": [
  "비밀번호는 10자 이상이여야 합니다."
  ],
  "error": "Bad Request",
  "statusCode": 400
}

{
  "message": "비밀번호는 숫자, 문자, 특수문자 중 2가지 이상을 포함해야 합니다.",
  "error": "Bad Request",
  "statusCode": 400
}

{
  "message": "비밀번호는 3회 이상 연속되는 문자 사용은 불가능합니다.",
  "error": "Bad Request",
  "statusCode": 400
}

### Fail(409)
{
  "message": "이미 존재하는 계정입니다.",
  "error": "Conflict",
  "statusCode": 409
}

{
  "message": "비밀번호와 비밀번호 확인이 일치하지 않습니다.",
  "error": "Conflict",
  "statusCode": 409
}

### 사용자 로그인
#### Request
```json
{
  "username": "test10",
  "password": "11234567890@@"
}
```

#### Response(201)
Set-Cookie: accessToken={JWT_TOKEN}
{
  "message": "로그인 성공",
  "data": {
    "id": 2,
    "username": "test09"
  }
}

#### Fail(401)
{
  "message": "비밀번호가 일치하지 않습니다.",
  "error": "Unauthorized",
  "statusCode": 401
}

{
  "message": "존재하지 않는 계정입니다.",
  "error": "Unauthorized",
  "statusCode": 401
}

2023-11-02 12:15 UTC, dawwson approved these changes
고생하셨습니다 👍

2023-11-02 12:15 UTC, dawwson commented on src/feature/auth/auth.controller.ts
> +    });
그냥 질문입니당~~ 회원가입 성공했을 때 username이랑 비밀번호 유효한지 여부를 리턴해주는 이유가 있으신가요? 보통 회원가입이 성공하면 프론트엔드 쪽에서 로그인 페이지로 유도하게 되니까요... 어떤 용도인지 궁금합니다!

2023-11-02 12:38 UTC, laetipark commented on src/feature/auth/auth.controller.ts
> +    });
출력 용으로 띄우려고 넣은 거긴 한데, 정상적으로 데이터 Database에 삽입하고 data에 username 관련 정보 있으면, 로그인 페이지 넘어가면서 아이디만 자동으로 입력해주는 식으로 표시해도 괜찮을 거 같긴 하네요 :)

수정하겠습니다!

2023-11-02 17:01 UTC, kangssu approved these changes
고생하셨습니다! 
전 sign-up, sign-in 관련 코멘트 뿐이라서 수정만 해주시면 될 것 같아요!
우선 approve 해놓겠습니다! 🙏

2023-11-02 17:01 UTC, kangssu commented on src/feature/auth/auth.controller.ts
> +  @Post('signup')
여기 sign-up이 더 좋을 것 같아용!

2023-11-02 17:01 UTC, kangssu commented on src/feature/auth/auth.controller.ts
> +  @Post('signin')
여기도 sign-in이 더 좋아보여용! 😄

2023-11-02 17:01 UTC, kangssu commented on src/enum/successType.enum.ts
> +  USER_SIGNUP = '회원가입 성공',
여기도 USER_SIGN_UP, USER_SIGN_IN이 더 좋아보여요!

2023-11-03 00:05 UTC, sayapin1 commented on src/feature/auth/auth.service.ts
> +  }
이 getAccessToken 코드를 서비스까지 가져오지 않고 컨트롤러에서 바로 return await this.jwtService.signAsync(payload); 해버려도 되지 않나요? 
서비스레이어에서 하고 있는 부분은 딱히 없어보여서용.
만약 서비스에서 해야 한다면, 코드를 아래와 같이 바꾸면 더 깔끔할 것 같아요
```
async getAccessToken(payload) {
  return await this.jwtService.signAsync(payload) 
}
```

2023-11-03 00:05 UTC, sayapin1 commented on src/feature/auth/auth.controller.ts
> +      data: { creatableUser, passwordValid },
creatableUser라는 리턴값의 필요성을 모르겠어용..!
회원가입할 때는 성공했다는 메세지만으로 충분하지 않을까요?
만약 리턴값이 필요하다면, 그냥 바로 signupUserDto.username에서 가져와도 되는 거 아닐까요?
그리고 변수명이 creatableUser인데 정확히 뭘 말하는 건지 모르겠어서, 변수명도 바꾸면 좋을 것 같아욤

2023-11-03 05:38 UTC, tomeee11 approved these changes

2023-11-03 09:06 UTC, sayapin1 requested changes
제가 쓴 리뷰 중 하나는 해결이 된 것 같아서..! 다른 하나만 확인 부탁드립니당

2023-11-03 12:03 UTC, laetipark commented on src/feature/auth/auth.service.ts
> +  }
차라리 이런 코드가 더 괜찮군요! 수정하겠습니다 :)

2023-11-03 12:14 UTC, sayapin1 approved these changes

2023-11-03 12:45 UTC, merged