맛집 상세정보 가져오기
Wanted-Pre-Onboarding-Team-E/lets-go-here pull request #18
Opened 2023-11-04 18:01 UTC by sayapin1

## 🚀 이슈 번호
#14 맛집 상세 정보 가져오기

<br>

## 💡 변경 이유
맛집 상세 정보를 가져오고 조회수를 1 올리는 코드 작성 
<br>

## 🔑 주요 변경사항

1. 맛집 조회수 올리기
2. 올린 후 맛집 상세 정보 가져오기

원래는 맛집 정보 가져오기(그리고 가져온 데이터가 없을 시 오류 발생) -> 조회수 올리기 -> 조회수를 올린 정보를 다시 가져오기 로직으로 만들려고 했으나,
맛집 테이블 데이터가 너무 많아서... 혹시라도 불러오는 시간이 조금이라도 늦어질 수 있는 가능성이 걱정되어 일단 조회수를 올리고 update된 정보가 없을 경우 에러를 발생시키고 그 다음에 제대로 된 맛집 정보를 가져오도록 코드를 작성했습니다. 

원래 find메서드로 맛집 정보를 가져오려 했으나 코드가 너무 길어져 createQueryBuilder로 수정했습니당

<br>

## 📷 테스트 결과

2023-11-05 06:48 UTC, kangssu approved these changes
고생하셨습니다! 😄 간단한 코멘트 2개밖에 없어서 approve 해놓겠습니다!
(머지전에만 수정 부탁드려용)

2023-11-05 06:48 UTC, kangssu commented on src/feature/restaurant/restaurant.controller.ts
>    getRestaurants() {
요거 아마 스켈레톤 만들때 임시로 작성한 함수 같은데용!
삭제부탁드려용 😢

2023-11-05 06:48 UTC, kangssu commented on src/feature/restaurant/restaurant.service.ts
> +  async AddRestaurantViewCountById(id: number): Promise<any> {
AddRestaurantViewCountById 함수명에서 맨 앞에 A만 규칙에 맞게 소문자로 변경부탁드려용 😄 (addRestaurantViewCountById)

2023-11-05 06:57 UTC, dawwson requested changes
고생하셨습니다!

2023-11-05 06:57 UTC, dawwson commented on src/feature/restaurant/restaurant.service.ts
> +      .getOne();
평가 생성일 내림차순(최신순) 조건도 들어가야 할 거 같아요!

2023-11-05 09:38 UTC, dawwson approved these changes

2023-11-05 09:43 UTC, sayapin1 commented on src/feature/restaurant/restaurant.service.ts
> +  async AddRestaurantViewCountById(id: number): Promise<any> {
헉 왜 대문자로 됐지,,, 감사해용

2023-11-05 09:44 UTC, sayapin1 commented on src/feature/restaurant/restaurant.controller.ts
>    getRestaurants() {
혹시 몰라서 일단 남겨뒀는데 지우겠습니당

2023-11-05 09:44 UTC, sayapin1 commented on src/feature/restaurant/restaurant.service.ts
> +      .getOne();
오 그러는 게 맞는 것 같아요 수정하겠습니다!

2023-11-05 13:10 UTC, laetipark approved these changes
고생 많으십니다 :) 코드 잘 확인하고 갑니다!

2023-11-06 00:28 UTC, tomeee11 approved these changes

2023-11-06 01:10 UTC, merged