맛집 조회 API
Wanted-Pre-Onboarding-Team-E/lets-go-here pull request #24
Opened 2023-11-06 12:15 UTC by laetipark

## 🚀 이슈 번호
<br>

## 💡 변경 이유
<br>

## 🔑 주요 변경사항
<br>

## 📷 테스트 결과

2023-11-06 15:11 UTC, kangssu requested changes
고생하셨습니당! 😄 2가지 코멘트만 확인부탁드려요!

2023-11-06 15:11 UTC, kangssu commented on src/entity/restaurant.entity.ts
> +  isMultiUse!: string; // 다중이용업소여부
원래 boolean 타입이여서 is를 넣은거라 is는 빼주셔도 될 것 같습니다! 😄 
isMultiUse >  multiUse

2023-11-06 15:11 UTC, kangssu commented on src/feature/city/city.service.ts
> +      await this.schedulerService.updateCities();
스케줄러 서비스에 있는 updateCities 함수는 스케줄러로 자동으로 들어가는건데 여기서 호출한 이유가 있을까요?? 😮

2023-11-06 15:34 UTC, dawwson reviewed
와우 주석을 꼼꼼히 달아주셨네요 👍

2023-11-06 15:34 UTC, dawwson commented on src/feature/restaurant/restaurant.controller.ts
> +    });
그냥 리턴해버리는 건 어떠신가요

2023-11-06 15:34 UTC, dawwson commented on src/feature/restaurant/restaurant.controller.ts
> +    @Res() res: Response,
쿼리 DTO가 있으면 좋을 것 같군요....

2023-11-06 15:34 UTC, dawwson commented on src/feature/restaurant/restaurant.service.ts
> +              range * 1000
query로 range를 소수점으로 받지 않나요?

2023-11-06 15:34 UTC, dawwson commented on src/feature/restaurant/restaurant.service.ts
> +          );
정렬은 쿼리문에서 실행하는 게 어떠신가요...

2023-11-07 04:19 UTC, laetipark commented on src/feature/restaurant/restaurant.controller.ts
> +    });
다른 코드도 res.send로 처리했어서 바꿀 필요가 있다면, res.send로 처리하거나 return으로만 처리하는 거로 통일하겠습니다!

2023-11-07 04:24 UTC, laetipark commented on src/entity/restaurant.entity.ts
> +  isMultiUse!: string; // 다중이용업소여부
이러면 database에서 is_multi_use column명도 바꿔야 할까요?

2023-11-07 04:25 UTC, laetipark commented on src/feature/city/city.service.ts
> +      await this.schedulerService.updateCities();
캐시가 휘발성있고, 데이터를 지울 수도 있어가지고 데이터가 없을 경우 다시 캐시에 넣기 위해 호출하는 거로 설계해보았는데, 필요없을 거 같다면 지우겠습니다!

2023-11-07 04:28 UTC, laetipark commented on src/feature/restaurant/restaurant.service.ts
> +          );
제가 filter하고 정렬하는 거로 생각했는데 먼저 orderby로 db 정렬하고 filter로 불러도 괜찮을 거 같네요!

2023-11-07 05:09 UTC, kangssu commented on src/entity/restaurant.entity.ts
> +  isMultiUse!: string; // 다중이용업소여부
@laetipark 
넵! DB 테이블 컬럼명도 multi_use 로 가는게 좋을 것 같습니다 😄 (노션에는 방금 수정해놨습니다!)

2023-11-07 05:25 UTC, laetipark commented on src/feature/restaurant/restaurant.service.ts
> +          );
정렬을 쿼리문에서 실행하려고 했는데, 거리순으로 정렬할 경우에 db에서의 위,경도와 현재 위, 경도의 차이를 구해서 정렬하도록 설계해야하는데 db에서 위, 경도 값을 쿼리로 부르는 방법을 모르겠네요...

2023-11-07 05:47 UTC, dawwson commented on src/feature/restaurant/restaurant.service.ts
> +          );
아하 거리순에 쿼리가 있었군요...😓 저도 이 부분 쿼리로 해결하는 방법 찾아보고 있긴 한데 아직 테스트를 안 해봐서 확답을 못 드리겠네요 ㅠㅠ 그러면 원래 작성한대로 두시고, TODO 주석 같은 것만 남겨주셔도 될 거 같습니다!!

2023-11-07 06:29 UTC, kangssu commented on src/feature/city/city.service.ts
> +      await this.schedulerService.updateCities();
@laetipark 
아 요 내용 PR 커멘트 위에 작성해주셨는데 제가 제대로 안 읽었네요 😢 답변 감사합니다 🙏

동훈님이 말씀하신 설계 방법도 괜찮아보이긴 합니다!
다만, 레스토랑 서비스에서 스케줄러 서비스를 임포트 하고,
레스토랑 모듈에서 스케줄러 모듈을 임포트하는 부분 때문에 질문을 드렸었어용

스케줄러 서비스로 분리한 이유는 스케줄러 서비스 파일내에 @Cron 데코레이터가 달린 함수들을 작성하고
해당 함수들에서 실제 서비스 로직이 담긴 Lib을 임포트 하는 방식으로 나눈거였습니다!

예를들면 externalApiLib, restaurantLib를 SchedulerService 임포트하는 것으로
흐름은 SchedulerService  -> restaurantLib 또는 externalApiLib 파일에서 실제 로직을 구현하는 방식입니다!

그래서 아래 2가지 방식이 더 좋을 것 같다는 생각이 듭니다!
### 1. 해당 시군구 캐시 유효시간 두지 않기
저희가 시군구 csv 파일 자체를 프로젝트 내에 고정으로 넣어놨기 때문에,
시군구 관련 캐시는 유효기간을 두지 않고 캐시에 계속 저장해두고 스케줄러만 실행한다면 위에서 작성하신 
`await this.schedulerService.updateCities();` 이 코드와 레스토랑 모듈에 임포트한 스케줄러 모듈을 삭제하는 것이 좋아보입니다!
![이미지 1](https://github.com/Wanted-Pre-Onboarding-Team-E/geography-based-restaurant-recommendation/assets/83870420/215a654d-a018-4975-9944-adb6f87335e0)

### 2. 스케줄러 서비스 내에 시군구 CSV 파일 파싱하여 캐시 저장 로직 분리
현재 스케줄러 서비스의 updateCities 함수내에 시군구 CSV 파일 파싱 > 캐시 저장하는 로직이 들어가있던데
이거를 externalApiLib 파일로 로직을 옮겨서 아래처럼 작성하는 것이 더 좋아보입니다!

**SchedulerService 파일**
```
 /** 시군구 데이터 업데이트
   * 매주 월요일 정오에 시군구 데이터 업데이트 */
  @Cron('0 12 * * * 1')
  async updateCities() {
   this.externalApiLib.updateCities();
  }
```

**externalApiLib 파일**
```
updateCities(){
 const filePath = path.join(__dirname, '../../../csv', 'sgg_lat_lon.csv');

    const data = [];
    fs.createReadStream(filePath)
      .pipe(csv())
      .on('data', (row) => {
        data.push({
          city: row['do-si'],
          district: row['sgg'],
          latitude: row['lat'],
          longitude: row['lon'],
        });
      })
      .on('end', () => {
        this.cacheManager.set(`city`, data);
      })
      .on('error', (error) => {
        Logger.error(error.message);
      });
}
```
</br>

사실 제 생각에는 1번인 시군구만 캐싱의 유효기간을 없애서 유지해서 스케줄러로 새로운 캐싱 값으로만 업데이트 해주고
`await this.schedulerService.updateCities();` 요 코드랑 레스토랑 모듈에 임포트한 스케줄러모듈을 삭제 + 스케줄러 서비스에 임포트한 스케줄러 서비스 삭제 가 좋아보이긴 합니다..

만약..1번이 안된다면 2번으로 가서 `await this.schedulerService.updateCities();` 이 코드를 `await this.externalApiLib.updateCities();` 이렇게 고치는 것이 좋아보입니다! 🙏

2023-11-07 07:04 UTC, laetipark commented on src/feature/city/city.service.ts
> +      await this.schedulerService.updateCities();
제 생각은 2번 방법이 좋을 거 같아요! 제가 알기로는 `Cron` 데코레이터가 프로그램 시작 시에 바로 실행되는 것이 아닌 거로 알고 있어서 만약 **캐시 데이터가 없는데 시군구 호출을 사용할 경우** 아무것도 불러오지 못하는 문제가 생겨 추후에 지역 필터링 기능 추가하는 데 문제가 생길 거 같아요. 2번 방법처럼 고쳐보겠습니다!

2023-11-07 07:27 UTC, tomeee11 approved these changes

2023-11-07 07:29 UTC, kangssu approved these changes
저 스케줄러 모듈에 exports 되있는 부분만 삭제 코멘트 달아서 고것만 수정 부탁드려요!
나머지는 확인했습니당 😄 제가 드렸던 코멘트에 대해 빠르게 피드백 주시고 반영해주셔서 감사합니다! 🙏

2023-11-07 07:29 UTC, kangssu commented on src/feature/scheduler/scheduler.module.ts
> +  exports: [SchedulerService],
exports 삭제해주셔도 될 것 같습니당!

2023-11-07 07:31 UTC, laetipark commented on src/feature/scheduler/scheduler.module.ts
> +  exports: [SchedulerService],
꼼꼼하게 확인해주셔서 감사합니다! 바로 처리하겠습니다 😮

2023-11-07 07:36 UTC, sayapin1 approved these changes
수고하셨습니다!

2023-11-07 08:53 UTC, dawwson approved these changes

2023-11-07 09:36 UTC, merged