맛집 평가 API 생성
Wanted-Pre-Onboarding-Team-E/lets-go-here pull request #9
Opened 2023-11-01 09:42 UTC by tomeee11

## 🚀 이슈 번호
<br>
#8  맛 평가 API 생성
## 💡 변경 이유
<br>

![12없음](https://github.com/Wanted-Pre-Onboarding-Team-E/geography-based-restaurant-recommendation/assets/114478045/190d1103-bc9c-4fd0-922f-1bce2536b17a)

## 🔑 주요 변경사항
<br>

## 📷 테스트 결과

![요청](https://github.com/Wanted-Pre-Onboarding-Team-E/geography-based-restaurant-recommendation/assets/114478045/f5b945d3-d55a-4702-9add-3d677273c045)

2023-11-02 12:36 UTC, laetipark commented on src/feature/restaurant/restaurant.service.ts
> +      throw new NotFoundException('음식점을 찾을 수 없습니다.');
에러 메시지 failType.enum에 정리하는 거로 알고 있는데 확인 부탁드려요!

2023-11-02 16:53 UTC, kangssu requested changes

2023-11-02 16:53 UTC, kangssu commented on src/entity/restaurant.entity.ts
> +  @OneToMany(() => Review, (review) => review.restaurant, { cascade: true })
제가 cascade 옵션을 사용해보지 않아서 궁금한 점이 있습니당
만약, 아래의 내용이 있다고 가정할때 reviewId 2를 지웠을 경우 restaurantId 2가 지워지는 개념인가요..? 😮 
1. reviewId=1, restaurantId=2
2. reviewId =2, restaurantId=2

2023-11-02 16:53 UTC, kangssu commented on src/feature/custom/apiResult.ts
> +type SuccessResult<T> = T extends void
저희 리턴 값을 아래처럼 주기로 했어서 해당 파일은 삭제하는 것이 나을 것 같아요!
이건 제가 초반에 success: true로 사용했는데 팀 회의에서 이 방법보다는 메세지와 데이터만 리턴하기로 얘기했던 걸로 기억합니다!
```
// 데이터가 있을 경우
{
  message: SuccessType.USER_SAVE,
  data: [
    {...}, {...}
  ]
	data: {..}
}

// 데이터가 없을 경우
{
  message: SuccessType.USER_SAVE
}
```

2023-11-02 16:53 UTC, kangssu commented on src/feature/restaurant/dto/createReviewDto.ts
> +  @IsInt()
1. IsNumber()와 IsInt()를 같이 사용하신 이유가 있나요?
2. IsNotEmpty()는 ! 이거와 동일한 기능을 하는 것 같은데 명시한 이유가 있을까요?

2023-11-02 16:53 UTC, kangssu commented on src/feature/restaurant/restaurant.service.ts
> +    private readonly reviewService: ReviewService,
여기서 ReviewService 쓰시는것보다 차라리 리뷰 레포 바로 써버리는게 어떨까요?
리뷰는 여기서 등록이랑 가져오는것 뿐이라.. 피쳐단위로 분리될 필요는 없어보이기도하고,
이걸 세분화시켜서 모듈화 하거나, Lib으로 만드는 것보다 심플하게 가버리는 게 괜찮아보여서요! 😶

여기서 리뷰 레포 바로쓰면 레스토랑 모듈에 providers 안에 ReviewService는 삭제될 수 있어서용
```
@InjectRepository(Review)
    private readonly reviewRepository: Repository<Review>,
```

@laetipark @dawwson @sayapin1 
위 내용 같이 확인부탁드려요! 🙏

2023-11-02 16:53 UTC, kangssu commented on src/feature/restaurant/review.service.ts
> +      user: { id: userId },
여기 userId: userId 로 작성해도 되지 않아용??
```
userId: userId,
restaurantId: restaurantId
...
```

2023-11-03 05:44 UTC, dawwson commented on src/feature/restaurant/restaurant.service.ts
> +    private readonly reviewService: ReviewService,
넵 저도 하나의 서비스에서 여러 레포 불러오는게 더 심플해보입니다!

2023-11-03 09:04 UTC, sayapin1 commented on src/feature/restaurant/restaurant.service.ts
> +    return createReview;
이 createReview라는 리턴값이 reviewService의 createReview의 리턴값을 담은 건데 정작 createReview함수에는 리턴값이 없어용. 그리고 여기서 이렇게 리턴해도 restaurantController에선 그걸 받지 않아요. 그렇다면 애초에 return createReview라는 코드를 빼버려도 똑같이 동작하지 않을까요?

2023-11-03 09:07 UTC, sayapin1 requested changes
고생하셨습니당! 전 크게 수정할 게 없어보여서 제가 커멘트한 몇가지만 확인 부탁드릴게용

2023-11-04 03:45 UTC, laetipark commented on src/enum/failType.enum.ts
> -  AUTH_INVALID_TOKEN = '유효하지 않은 토큰입니다.',
이거 그대로 병합하면 제 코드가 사라지게 되어서 main 브랜치와 병합하고 커밋 부탁드릴 수 있을까요?

2023-11-04 05:03 UTC, dawwson reviewed
고생하셨습니다!

2023-11-04 05:03 UTC, dawwson commented on src/feature/review/review.controller.ts
> +    @Param('userId', ParseIntPipe) userId: number,
동훈님의 회원가입/로그인 PR이 머지되어서 지금 반영해주셔도 좋을 것 같습니다!

2023-11-04 05:03 UTC, dawwson commented on src/feature/review/review.service.ts
> +    restaurant.totalRating = avgRating;
select AVG(rating) from reviews 쿼리로 가져와도 괜찮을 거 같네용

2023-11-04 11:08 UTC, sayapin1 approved these changes

2023-11-04 11:09 UTC, kangssu requested changes

2023-11-04 11:09 UTC, kangssu commented on src/feature/restaurant/restaurant.service.ts
> +  async findOneBy(restaurantId: number): Promise<Restaurant> {
findOneBy 함수명을 getRestaurantById 요렇게 변경하면 더 좋을 것 같습니당 😄 
findOneBy라고만 하면 어떤걸 가져오는지 명확하지 않기 때문입니다!

2023-11-04 11:09 UTC, kangssu commented on src/feature/review/review.controller.ts
> +    //NOTE: userId 값은 추후에 Param -> Req로 변경.
//NOTE 주석은 지워주세요! 수정한걸로 보입니다!

2023-11-04 11:09 UTC, kangssu commented on src/feature/review/review.controller.ts
> +    //NOTE: userId 값은 추후에 Param -> Req로 변경.
postReviewOfRestaurantById 함수명을 ->>> createReviewByRestaurantId 요렇게 고치면 어떨까요?
만든다 / 리뷰 / 레스토랑 아이디 기준 요런 느낌입니당!

2023-11-04 11:45 UTC, laetipark approved these changes
고생 많으십니다! 즐거운 주말 보내세요 :)

2023-11-05 06:51 UTC, kangssu approved these changes

2023-11-06 00:11 UTC, dawwson approved these changes

2023-11-06 00:27 UTC, merged